---
- name: "get inv"
  command: echo "{{ inventory_hostname }}"
- name: Create DNS zone from the infra
  route53:
    state: present
    zone: "{{ DNS_ZONE }}"
    record: "{{ DNS_NAME }}.{{ DNS_ZONE }}"
    type: A
    ttl: 7200
    value: "{{ ec2.results[0].instances[0].public_ip_address}}"
    wait: yes
